version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: aslikeme/backend:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - ${Back_port}:3001
    networks:
      - backend_network
      - frontend_network

  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aslikeme/frontend:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - ${Front_port}:3000  
    networks:
      - frontend_network

  database:

    build:
      context: ./database
      dockerfile: Dockerfile
    image: aslikeme/database:latest
    restart: unless-stopped
    ports:
      - ${DB_port}:5432
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge
  
  frontend_network:  
    driver: bridge

volumes:
  postgres_data:
