version: "3"
services:
  backend:

    depends_on:
      - database
    ports:
      - ${Back_port}:3001
    networks:
      - backend_network
      - frontend_network

  frontend:

    depends_on:
      - database
    ports:
      - ${Front_port}:3000  
    networks:
      - frontend_network

  database:
    ports:
      - ${DB_port}:5432
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
  
  frontend_network:  
    driver: bridge

volumes:
  postgres_data:
